'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports CrystalDecisions.CrystalReports.Engine
Imports CrystalDecisions.ReportSource
Imports CrystalDecisions.Shared
Imports System
Imports System.ComponentModel


Public Class CR0201P1
    Inherits ReportClass
    Private lstColumn As List(Of String)
    Public Sub New(ByVal colunmValue As List(Of String))
        MyBase.New()
        lstColumn = colunmValue
        Call setStyle()
    End Sub
    Private Sub setStyle()
        Dim iLst As Integer
        Dim iCounter As Integer
        Dim curNum As Integer
        Dim lastNum As Integer
        For iLst = 0 To 30
            DirectCast(Me.ReportDefinition.ReportObjects.Item(("i" & iLst.ToString) + "1"), FieldObject).Left = iLst * 300
            DirectCast(Me.ReportDefinition.ReportObjects.Item(("i" & iLst.ToString) + "1"), FieldObject).Width = 1080
            DirectCast(Me.ReportDefinition.ReportObjects.Item(("t" & iLst.ToString) + "1"), FieldObject).Left = iLst * 300 + 30
            DirectCast(Me.ReportDefinition.ReportObjects.Item(("t" & iLst.ToString) + "1"), FieldObject).Width = 1080
            DirectCast(Me.ReportDefinition.ReportObjects.Item(("t" & iLst.ToString) + "1"), FieldObject).Top = 120
        Next
        curNum = 0
        For iLst = 0 To lstColumn.Count - 1
            Select Case lstColumn(iLst)
                Case "社員番号"
                    iCounter = 3
                Case "名前"
                    iCounter = 5
                Case "役職"
                    iCounter = 5
                Case "電話番号1"
                    iCounter = 5
                Case "組合支部"
                    iCounter = 2
                Case "機種略称"
                    iCounter = 2
                Case "資格"
                    iCounter = 2
                Case "メール"
                    iCounter = 3
                Case "備考"
                    iCounter = 4
                Case Else
                    iCounter = 0
            End Select
            If iCounter <> 0 Then
                lastNum = iLst
                DirectCast(Me.ReportDefinition.ReportObjects.Item(("t" & CStr(curNum) + "1")), FieldObject).Width = iCounter * 300
                If curNum + iCounter < 31 Then
                    For mm As Integer = curNum To curNum + iCounter - 2
                        DirectCast(Me.ReportDefinition.ReportObjects.Item(("Line" & (mm + 100).ToString)), LineObject).ObjectFormat.EnableSuppress = True
                    Next
                Else
                    For mm As Integer = curNum To 29
                        DirectCast(Me.ReportDefinition.ReportObjects.Item(("Line" & (mm + 100).ToString)), LineObject).ObjectFormat.EnableSuppress = True
                    Next
                End If
                curNum = curNum + iCounter
            End If
        Next
        If curNum < 31 Then

            For nn As Integer = lastNum To 29
                DirectCast(Me.ReportDefinition.ReportObjects.Item(("Line" & (nn + 100).ToString)), LineObject).ObjectFormat.EnableSuppress = True
            Next
            DirectCast(Me.ReportDefinition.ReportObjects.Item(("t" & CStr(lastNum) + "1")), FieldObject).Width = (31 - lastNum) * 300
        End If
    End Sub

    Public Overrides Property ResourceName() As String
        Get
            Return "CR0201P1.rpt"
        End Get
        Set
            'Do nothing
        End Set
    End Property
    
    Public Overrides Property NewGenerator() As Boolean
        Get
            Return true
        End Get
        Set
            'Do nothing
        End Set
    End Property
    
    Public Overrides Property FullResourceName() As String
        Get
            Return "UnionAct.CR0201P1.rpt"
        End Get
        Set
            'Do nothing
        End Set
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public ReadOnly Property Section1() As CrystalDecisions.CrystalReports.Engine.Section
        Get
            Return Me.ReportDefinition.Sections(0)
        End Get
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public ReadOnly Property Section2() As CrystalDecisions.CrystalReports.Engine.Section
        Get
            Return Me.ReportDefinition.Sections(1)
        End Get
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public ReadOnly Property GroupHeaderSection1() As CrystalDecisions.CrystalReports.Engine.Section
        Get
            Return Me.ReportDefinition.Sections(2)
        End Get
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public ReadOnly Property GroupHeaderSection2() As CrystalDecisions.CrystalReports.Engine.Section
        Get
            Return Me.ReportDefinition.Sections(3)
        End Get
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public ReadOnly Property Section3() As CrystalDecisions.CrystalReports.Engine.Section
        Get
            Return Me.ReportDefinition.Sections(4)
        End Get
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public ReadOnly Property GroupFooterSection1() As CrystalDecisions.CrystalReports.Engine.Section
        Get
            Return Me.ReportDefinition.Sections(5)
        End Get
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public ReadOnly Property Section4() As CrystalDecisions.CrystalReports.Engine.Section
        Get
            Return Me.ReportDefinition.Sections(6)
        End Get
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public ReadOnly Property Section5() As CrystalDecisions.CrystalReports.Engine.Section
        Get
            Return Me.ReportDefinition.Sections(7)
        End Get
    End Property
End Class

<System.Drawing.ToolboxBitmapAttribute(GetType(CrystalDecisions.[Shared].ExportOptions), "report.bmp")>  _
Public Class CachedCR0201P1
    Inherits Component
    Implements ICachedReport
    
    Public Sub New()
        MyBase.New
    End Sub
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Overridable Property IsCacheable() As Boolean Implements CrystalDecisions.ReportSource.ICachedReport.IsCacheable
        Get
            Return true
        End Get
        Set
            '
        End Set
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Overridable Property ShareDBLogonInfo() As Boolean Implements CrystalDecisions.ReportSource.ICachedReport.ShareDBLogonInfo
        Get
            Return false
        End Get
        Set
            '
        End Set
    End Property
    
    <Browsable(false),  _
     DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Overridable Property CacheTimeOut() As System.TimeSpan Implements CrystalDecisions.ReportSource.ICachedReport.CacheTimeOut
        Get
            Return CachedReportConstants.DEFAULT_TIMEOUT
        End Get
        Set
            '
        End Set
    End Property
    
    Public Overridable Function CreateReport() As CrystalDecisions.CrystalReports.Engine.ReportDocument Implements CrystalDecisions.ReportSource.ICachedReport.CreateReport
        Dim rpt As CR0201P1 = New CR0201P1(Nothing)
        rpt.Site = Me.Site
        Return rpt
    End Function
    
    Public Overridable Function GetCustomizedCacheKey(ByVal request As RequestContext) As String Implements CrystalDecisions.ReportSource.ICachedReport.GetCustomizedCacheKey
        Dim key As [String] = Nothing
        '// The following is the code used to generate the default
        '// cache key for caching report jobs in the ASP.NET Cache.
        '// Feel free to modify this code to suit your needs.
        '// Returning key == null causes the default cache key to
        '// be generated.
        '
        'key = RequestContext.BuildCompleteCacheKey(
        '    request,
        '    null,       // sReportFilename
        '    this.GetType(),
        '    this.ShareDBLogonInfo );
        Return key
    End Function
End Class
